import { PrismaClient } from "@prisma/client"
const prisma = new PrismaClient()

async function main() {
  const courses = [
    // ─── TDLR CE APPROVED ───
    { id: "texas-cosmetology-laws", title: "Texas Cosmetology Laws & Rules 2025", description: "Complete overview of TDLR regulations, Texas Occupations Code, and the rules governing cosmetology practice in Texas. Required for license renewal.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 120, level: "beginner", isTdlrApproved: true, tdlrHours: 2.0, isFeatured: true, videoUrl: "ZB9oEKB0gUs" },
    { id: "hiv-aids-prevention", title: "HIV/AIDS & Communicable Disease Prevention", description: "TDLR-required training on HIV/AIDS awareness, bloodborne pathogens, and communicable disease prevention in the salon environment.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "Nf1skRgNPgU" },
    { id: "sanitation-disinfection", title: "Sanitation & Disinfection Protocols", description: "Proper disinfection procedures for salon tools, implements, and surfaces. Texas sanitation requirements and EPA-registered disinfectant guidelines.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "5-jG5EcFxKI" },
    { id: "chemical-safety-osha", title: "Chemical Safety & OSHA Compliance", description: "Safe handling of chemical salon products, MSDS sheets, ventilation requirements, and OSHA compliance for cosmetology professionals.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "8TkFiKHBaHs" },
    { id: "professional-ethics", title: "Professional Ethics in Cosmetology", description: "Client relationships, professional boundaries, honest pricing, and ethical business practices for Texas cosmetology professionals.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "ydSHXrSLqBo" },
    { id: "workplace-accidents", title: "Preventing Workplace Accidents", description: "Ergonomics, repetitive stress injury prevention, slip and fall prevention, and workplace safety for salon professionals.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "kK9ZJMR0lhc" },
    { id: "consumer-protection", title: "Consumer Protection Laws", description: "Texas consumer protection regulations, client rights, refund policies, and complaint procedures in the cosmetology industry.", category: "tdlr_ce", instructor: "TDLR Education", durationMinutes: 60, level: "beginner", isTdlrApproved: true, tdlrHours: 1.0, isFeatured: false, videoUrl: "Q5ggBHl3F-o" },
    // ─── COLOR ───
    { id: "balayage-fundamentals", title: "Balayage Fundamentals", description: "Master the art of balayage from sectioning to toning with Guy Tang. Freehand painting, foilayage, and achieving dimensional blondes. One of the most-watched color tutorials online.", category: "color", instructor: "Guy Tang", durationMinutes: 45, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "JuDNr9TYAJQ" },
    { id: "color-correction-masterclass", title: "Color Correction Masterclass", description: "Advanced color correction by Brad Mondo — removing box dye, lifting dark color, correcting banding, and achieving even results. Over 10 million views.", category: "color", instructor: "Brad Mondo", durationMinutes: 40, level: "advanced", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "D5vz3PoH6kQ" },
    { id: "shades-eq-formulation", title: "Redken Shades EQ Formulation Guide", description: "Complete Shades EQ formulation guide by Redken — toning, glossing, refreshing color, and achieving consistent results. The most comprehensive Shades EQ tutorial available.", category: "color", instructor: "Redken Education", durationMinutes: 35, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "tqLT2IGSQ3k" },
    { id: "toning-glazing", title: "Toning & Glazing Techniques", description: "Perfect every blonde with professional toning. Purple, blue, and neutral toners, timing, and maintenance recommendations from a master colorist.", category: "color", instructor: "Kenra Professional", durationMinutes: 28, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "8nCqFqBiNYU" },
    { id: "highlights-foiling", title: "Full Head Highlights & Foiling", description: "Step-by-step full head highlight application with foils. Sectioning patterns, placement strategies, and toning for the perfect blonde result.", category: "color", instructor: "Sam Villa", durationMinutes: 52, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "MNkjMrRjpLQ" },
    { id: "money-piece-technique", title: "Money Piece & Face Framing Color", description: "The most-requested salon service — how to execute a perfect money piece and face framing highlights. Bleach placement, toning, and blending techniques.", category: "color", instructor: "Guy Tang", durationMinutes: 22, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "3vy4YTEJ9RI" },
    // ─── CUTTING ───
    { id: "bob-lob-precision", title: "Precision Bob & Lob Haircut", description: "Step-by-step precision cutting for bobs and lobs by Sam Villa. Sectioning, elevation, and finishing for a clean result every time. One of the most watched cutting tutorials.", category: "cutting", instructor: "Sam Villa", durationMinutes: 38, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "wAHKx0dRqGE" },
    { id: "textured-curly-cutting", title: "Cutting Curly & Textured Hair", description: "Expert techniques for cutting naturally curly and coily hair. Curl typing, dry cutting vs wet cutting, and achieving shape without disrupting curl pattern.", category: "cutting", instructor: "Vernon Fran\u00e7ois", durationMinutes: 45, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "QZLS-XOkIkc" },
    { id: "blowout-mastery", title: "Blowout & Styling Mastery", description: "Perfect blowouts from start to finish by Chris Appleton. Round brush technique, tension, heat management, and long-lasting results. Used by Kim K and JLo.", category: "cutting", instructor: "Chris Appleton", durationMinutes: 25, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "OZ1D-4zMGwI" },
    { id: "layers-face-framing", title: "Layered Haircut with Face Framing", description: "How to cut layers and face framing to complement any face shape. Elevation, overdirection, and graduation techniques for professional results.", category: "cutting", instructor: "Sam Villa", durationMinutes: 42, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "6-JGsLLqiXA" },
    // ─── TEXTURE ───
    { id: "keratin-treatment", title: "Keratin Treatment Application", description: "Professional keratin treatment from start to finish. Preparation, sectioning, processing, and aftercare. Safety protocols and formaldehyde-free options explained.", category: "texture", instructor: "Brazilian Blowout Education", durationMinutes: 55, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "rNGLqVXjEiI" },
    { id: "olaplex-bond-building", title: "Olaplex Bond Building Treatment", description: "How to use Olaplex No. 1 through No. 9 professionally. In-salon treatment protocols, pricing, and client education for maximum results.", category: "texture", instructor: "Olaplex Education", durationMinutes: 30, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "Q9hGf3v1JRE" },
    // ─── BUSINESS ───
    { id: "building-clientele", title: "Building Your Clientele from Zero", description: "Proven strategies to grow your book from zero — client retention, referral programs, rebooking rates, and how to move clients when you change salons.", category: "business", instructor: "Salon Business Education", durationMinutes: 38, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "nLBCj64s0_4" },
    { id: "social-media-stylists", title: "Social Media Strategy for Stylists", description: "Instagram Reels, before/afters, hashtags, and converting followers into paying clients. The exact strategy used by stylists with 100k+ followers.", category: "business", instructor: "Salon Business Education", durationMinutes: 32, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "NcIiq6OB0mA" },
    { id: "pricing-for-profit", title: "Pricing Your Services for Profit", description: "How to calculate your true hourly rate, when and how to raise prices, and how to communicate price increases to clients without losing them.", category: "business", instructor: "Salon Business Education", durationMinutes: 28, level: "beginner", isTdlrApproved: false, tdlrHours: 0, isFeatured: true, videoUrl: "bMFNhMhSMmg" },
    { id: "suite-owner-transition", title: "Going from Commission to Suite Owner", description: "Step-by-step guide to transitioning from commission stylist to independent suite owner. Finances, licensing, equipment, and building your own brand.", category: "business", instructor: "Salon Business Education", durationMinutes: 45, level: "intermediate", isTdlrApproved: false, tdlrHours: 0, isFeatured: false, videoUrl: "Wj0iqEJf_Xo" },
  ]

  let created = 0
  for (const course of courses) {
    await prisma.eduCourse.upsert({
      where: { id: course.id },
      update: course,
      create: course,
    })
    created++
  }
  console.log(`Seeded ${created} courses with video IDs`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
